package org.mifra.core.api.orchestrator;

import org.mifra.core.api.models.domain.SagaStepMessage;
import org.mifra.core.api.models.external.ExternalReply;
import org.mifra.core.api.models.external.payloads.ExternalReplyBody;
import org.mifra.core.api.models.external.ExternalRequest;
import org.mifra.core.api.models.external.payloads.ExternalRequestBody;
import org.mifra.core.components.domain.messages.SagaStepHistory;
import org.mifra.core.components.stepmaps.SagaStepMap;

/**
 * Interface which represents the base that any business orchestrators derive from. It receives an ExternalRequest and
 * returns an ExternalReply to the request handler, each containing the formatted body parametrized with the
 * orchestrator implementation.
 * @param <I> The formatted request body received from the external request.
 * @param <O> The formatted reply body to send with the reply back to the client.
 */
public interface Orchestrator<I extends ExternalRequestBody, O extends ExternalReplyBody> {
    /**
     * Receive and handle an incoming request.
     * @param request The received request.
     * @return An ExternalReply object that will be sent back to the client.
     */
    SagaStepMessage<?> handleOncomingRequest(ExternalRequest<I> request);

    /**
     * Prepare the reply to return to the client when a saga finishes.
     * @param sagaStepHistory The collection of saga step messages generated by the saga.
     * @return The reply to be sent to the client.
     */
    ExternalReply<O> prepareExternalReply(SagaStepHistory sagaStepHistory);

    void defineStepMap(SagaStepMap stepMap);

}
