package org.mifra.core.components.dispatchers;

import org.mifra.core.api.models.domain.SagaStepMessage;
import org.mifra.core.components.domain.messages.SagaStepHistoryMap;
import org.mifra.core.components.invokers.ParticipantInvoker;
import org.mifra.core.components.registries.ParticipantRegistry;

/**
 * Dispatcher object that knows the participant registry and calls a given participant step execution.
 */
public class InProcessSagaDispatcher {

    private final ParticipantRegistry participantRegistry;

    public InProcessSagaDispatcher(ParticipantRegistry participantRegistry) {
        this.participantRegistry = participantRegistry;
    }

    /**
     * Fetch and call a given participant step execution.
     * @param stepLabel The step label associated to a given participant step.
     * @param historyMap The container which holds all the resulting objects from each executed step so far in the saga.
     * @return An step message generated by the participant step.
     */
    public SagaStepMessage<?> dispatch(String stepLabel, SagaStepHistoryMap historyMap) {

        ParticipantInvoker invoker = participantRegistry.getInvoker(stepLabel);

        if (invoker == null) {
            throw new IllegalArgumentException("No local handler found for label: " + stepLabel);
        }

        try {
            return invoker.delegate(historyMap);
        } catch (Throwable t) {
            throw new RuntimeException("Error executing participant step: " + stepLabel, t);
        }

    }
}
